version: "3"

services:

    htop:
        image: htop
        build: ./htop
        command: python app.py
        ports:
            - 80
        environment:
            VIRTUAL_HOST: "*/htop"

    tasks:
        image: tasks
        build: ./tasks
        command: python app.py
        ports:
            - 80
        environment:
            VIRTUAL_HOST: "*/tasks/*"
            FILE_STORAGE: /run/files
            DB_STORAGE: /run/db
        volumes:
            - file-storage:/run/files
            - database-storage:/run/db

    ui:
        image: ui
        build: ./ui
        ports:
            - 80
        environment:
            VIRTUAL_HOST: "*/ui, */ui*"

    lb:
        image: dockercloud/haproxy
        ports:
            - '80:80'
            - '1936:1936'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - htop
            - tasks
            - ui

volumes:
    file-storage:
    database-storage: